version: '2'
services:
  app:
    image: busybox:latest
    volumes:
      - ./:/var/www/html
  php:
    build: ./docker/php
    volumes_from:
      - app
    ports:
      - 8080:80
    links:
      - mysql
  mysql:
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
volumes:
  app: